# Generated by Django 5.0.6 on 2026-08-10 18:43

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=50, unique=True, verbose_name='Power plant type')),
                ('description', models.TextField(blank=True, help_text='What this kind of power plant is, and its role in Sweden')),
                ('icon', models.ImageField(blank=True, upload_to='category_icons/')),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Power plant type',
                'verbose_name_plural': 'Power plant types',
                'ordering': ['category_name'],
            },
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('place_name', models.CharField(max_length=100)),
                ('site', models.CharField(blank=True, max_length=254)),
                ('coordinates', models.CharField(blank=True, max_length=254)),
                ('info', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='place_images/')),
                ('active', models.BooleanField(default=True)),
                ('latitude', models.FloatField(validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)])),
                ('longitude', models.FloatField(validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)])),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='places', to='base.category')),
            ],
            options={
                'verbose_name': 'Power plant',
                'verbose_name_plural': 'Power plants',
                'ordering': ['place_name'],
            },
        ),
    ]
